### ISSUE TITLE
The updateRegion() method is not giving callback to didEnterRegion(region: CKSquareRegion) and didExitRegion(region: CKSquareRegion)

### ISSUE THREAD

**Issue by Shwetank97** [yveslym/Square-geofence-region#2]
The delegate method was working fine but all of sudden the updateRegion() method has stopped giving any call backs to didEnter or exit methods.

**Comment by yveslym** [comment]
Hi @Shwetank97 , I couldn't reproduce the the error, so maybe you should run the update location on background, so even if the app is close (not kill) the location can still update and you can receive get the callback from delegate

**Comment by Shwetank97** [comment]
Yeah, it is working fine in background mode, my application was being terminated by the OS and hence the callbacks disappeared.
